services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_AUTH_URL=https://quanticarch.com
    container_name: winder_website
    restart: always
    ports:
      - "9075:3000"
#     networks:
#       - dgobyke_net

# networks:
#   dgobyke_net:
#     driver: bridge
